### CRNPy example using Radiation Detection Technologies, Inc neutron detectors readings

In [1]:
import pandas as pd
import numpy as np
from crnpy import crnpy

In [2]:
df = pd.read_csv("calibration/rdt_stationary_lifoil/rdt.csv", names=['timestamp','pressure','RH', 'T','DP','BattVolt','counts_1','counts_2','counts_3','counts_total'])

In [3]:
df['timestamp'] = pd.to_datetime(df['timestamp'])


In [5]:
# Get counting times, both examples convert the df to valid 2d numpy arrays.
count_times_1, count_times_2, count_times_3 = crnpy.count_time(df[['counts_1','counts_2','counts_3']].T.to_numpy(), df['timestamp'])
#count_times_1, count_times_2, count_times_3=crnpy.count_time([df['counts_1'],df['counts_2'],df['counts_3']], df['timestamp'])

# Check counts for nan values in the counts
print("dectors with nan:", [df['counts_1'].isna().any(),df['counts_2'].isna().any(),df['counts_3'].isna().any()])

counts_1 = df['counts_1'].to_numpy()
counts_2 = df['counts_2'].to_numpy()
counts_3 = df['counts_3'].to_numpy()

print("Before filling nan:", np.isnan(counts_2).any())
print(counts_2[-20:])
# Fill nan values in detector 2
counts_2, counts = crnpy.fill_counts(counts_2, count_times_2, df['timestamp'].values)
print(counts_2[-20:])
print("After filling nan:", np.isnan(counts_2).any())


dectors with nan: [False, True, False]
Before filling nan: True
[ 743.  722.  753.  782.  784.  809.  744.  715.  766.  758. 1211.  924.
  823.  830.  837.  811.  818.  805.  720.  734.]


IndexError: invalid index to scalar variable.

In [8]:
!pip install ../

Processing c:\users\jperaza\documents\github\crnpy
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for crnpy: filename=crnpy-0.2.post12-py3-none-any.whl size=12566 sha256=74a33cc758d1dad657b4a39485467e8ac0f8ac8b571aefe824da085b2889b28c
  Stored in directory: C:\Users\jperaza\AppData\Local\Temp\pip-ephem-wheel-cache-_k77qoa5\wheels\f6\8d\b7\f6e2decef78c6e5165bd0aa5cfa78ff33fe08f7b23feaf279f
Successfully built crnpy
  Attempting uninstall: crnpy
    Found existing installation: crnpy 0.2.post12
    Uninstalling crnpy-0.2.post12:
      Successfully uninstalled crnpy-0.2.post12


In [10]:
df[['counts_1','counts_2','counts_3']].T.values

array([[  848,   436,   777, ...,   853,   857,   859],
       [  716,   720,   792, ...,   805,   720,   734],
       [  742,   796,   708, ..., 13004,  4352,  5684]], dtype=int64)

In [16]:
df[['counts_1','counts_2','counts_3']].T.to_numpy()

array([[  848,   436,   777, ...,   853,   857,   859],
       [  716,   720,   792, ...,   805,   720,   734],
       [  742,   796,   708, ..., 13004,  4352,  5684]], dtype=int64)

In [5]:
len(np.shape(counts_2))

1

In [12]:
df['counts_2'].to_numpy()[-20:]

array([ 743.,  722.,  753.,  782.,  784.,  809.,  744.,  715.,  766.,
        758., 1211.,  924.,  823.,   nan,  837.,  811.,  818.,  805.,
        720.,  734.])

In [5]:
count_times

array([[3600., 3600., 3600., ..., 3600., 3600., 3600.],
       [3600., 3600., 3600., ..., 3600., 3600., 3600.],
       [3600., 3600., 3600., ..., 3600., 3600., 3600.]])